[package]
name = "delayed-coding-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
delayed-coding = { path = ".." }

[features]
speculative-encode = ["delayed-coding/speculative-encode"]

[[bin]]
name = "codec"
path = "fuzz_targets/codec.rs"
test = false
doc = false
bench = false
